<a href="https://colab.research.google.com/github/Rana12408/machinelearning/blob/main/emlakfiyatlar%C4%B1n%C4%B1tahminetme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
df = pd.read_csv("/content/multilinearregression.csv", sep=";")
df


alan  odasayisi  binayasi   fiyat
0   180          5        10  510000
1   225          4        18  508000
2   260          3         2  548000
3   320          6        10  650000
4   335          4         9  628000
5   345          5        14  632000
6   355          3         0  680000
7   400          4        10  725000

In [ ]:
#linear regression modeli tanımlıyoruz
reg= linear_model.LinearRegression()
reg.fit(df[["alan","odasayisi","binayasi"]], df[["fiyat"]]) # Pass X and y as separate arguments

LinearRegression()

In [ ]:
reg.predict([[230,4,10]])
#230 metrekare 4 oda 10 binayaşı

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[530243.29284619]])

In [ ]:
reg.predict([[300,5,20]])
#300 metrekare 5 oda 20 binayaşı

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[590400.17941384]])

In [ ]:
# y=a+x1b1+x2b2+x3b3....
reg.coef_
#katsayıları hesaplar

array([[ 1018.99865454, 14893.82374984, -2606.68429997]])

In [ ]:
reg.intercept_
#sabit (a)

array([262365.15030321])